### PR TITLE
Add dynamic support for more levels of approval

### PR DESCRIPTION
**Pull request by Hipska**
This was discussed earlier with Combodo support. One of our customers wanted to be more flexible, so we came up with this dynamic approach.

image
image
image

### CODE REVIEW

**Comment by Hipska** [comment]
If you approve or accept this PR, I will improve more by adding the dicts and migration steps.

**Comment by Hipska** [comment]
@piRGoif any update on this?

**Comment by piRGoif** [comment]
Sorry, 2 months since you submitted this PR and we didn't planned a review with the product team yet. I'll see with them !

**Comment by piRGoif** [comment]
Hello,
We just did a review with the product team !
Sorry it took us so long :/

Well, this is a datamodel change, it implies migration for existing users... and this extension is bundled with Combodo's professional & essential packages.
Plus our clients didn't ask for such flexibility for now... 
Sometimes we had to give just one more approval level, but this can be done easily with a small customization.

For all of these reasons, we are not willing to integrate this in the default extension.

Many thanks though for sharing your work and offers us the possibility to merge it !

**Comment by Hipska** [comment]
Indeed a datamodel change, but as said, it can done by an automatic migration. It's just not added to the PR yet.

But, no problems, we [released it as module](https://github.com/Super-Visions/sv-approval-advanced) as wel. So if you have customers wanting this, you can forward them to us, we are happy to help them.

**Pull request closed without merging**
